# Generated by Django 5.1.4 on 2024-12-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'List'},
        ),
    ]
