# Generated by Django 5.1.4 on 2024-12-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_alter_list_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='note',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
