# Generated by Django 5.1.4 on 2024-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
