# Generated by Django 5.1.4 on 2024-12-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_anime_season_anime_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='titlerus',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
