# Generated by Django 5.1.4 on 2024-12-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0006_anime_titlerus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='titlerus',
            new_name='title_rus',
        ),
    ]
