# Generated by Django 5.1.4 on 2024-12-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0007_rename_titlerus_anime_title_rus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
