# Generated by Django 5.1.4 on 2024-12-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0008_alter_anime_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
