# Generated by Django 5.1.4 on 2024-12-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0009_alter_anime_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
