# Generated by Django 5.1.4 on 2024-12-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0010_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
