# Generated by Django 5.1.4 on 2024-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0011_alter_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('rating', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
